### ISSUE TITLE
thread 'main' panicked at 'Can't build UWS CAPI!'

### ISSUE THREAD

**Issue by YassinEldeeb** [GenrikhFetischev/async_uws#2]
when trying `examples/server.rs`, I get this:

```sh
  1 error generated.
  In file included from src/eventing/libuv.c:19:
  In file included from src/internal/internal.h:41:
  src/internal/eventing/libuv.h:23:10: fatal error: 'uv.h' file not found
  #include <uv.h>
           ^~~~~~
  1 error generated.
  In file included from src/crypto/openssl.c:28:
  In file included from src/internal/internal.h:41:
  src/internal/eventing/libuv.h:23:10: fatal error: 'uv.h' file not found
  #include <uv.h>
           ^~~~~~
  1 error generated.
  make: *** [capi] Error 1
  thread 'main' panicked at 'Can't build UWS CAPI!', /Users/yassineldeeb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libuwebsockets-sys-0.0.9/build.rs:48:7
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

my `build.rs` is as the following:
```rs
fn main() {
    println!("cargo:rustc-link-lib=z");
    println!("cargo:rustc-link-lib=uv");
    println!("cargo:rustc-link-lib=ssl");
    println!("cargo:rustc-link-lib=crypto");
    println!("cargo:rustc-link-lib=stdc++");
}

```

**Comment by GenrikhFetischev** [comment]
Do you have libuv installed in your system?

**Comment by YassinEldeeb** [comment]
I didn't have it before, but after installing it I got the following error:
```sh
  cargo:rerun-if-changed=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types/_uintmax_t.h
  cargo:rerun-if-changed=/Users/yassineldeeb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libuwebsockets-sys-0.0.9/uWebSockets/uSockets/src/libusockets.h
  /Library/Developer/CommandLineTools/usr/bin/make clean
  rm -f *.o HelloWorld HelloWorldAsync ServerName UpgradeSync UpgradeAsync EchoServer Broadcast BroadcastEchoServer RustHelloWorld libuwebsockets.a libuwebsockets.so
  cd ../uSockets && cc -pthread -DUWS_WITH_PROXY -DLIBUS_USE_OPENSSL -DLIBUS_USE_LIBUV -std=c11 -Isrc -flto -fPIC -O3 -c src/*.c src/eventing/*.c src/crypto/*.c

  --- stderr
  src/crypto/openssl.c:34:10: fatal error: 'openssl/ssl.h' file not found
  #include <openssl/ssl.h>
           ^~~~~~~~~~~~~~~
  1 error generated.
  make: *** [capi] Error 1
  thread 'main' panicked at 'Can't build UWS CAPI!', /Users/yassineldeeb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libuwebsockets-sys-0.0.9/build.rs:48:7
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I have openssl installed on my machine.

**Comment by YassinEldeeb** [comment]
Please let me know what I should have installed as of system dependencies,
and I'll also issue a PR with documentation update!

**Comment by GenrikhFetischev** [comment]
You need all the libraries your linking in build.rs to be installed in your system, so that would be: 
- libz
- libssl
- libcrypto
- libstdc++ (probably you already have this one)

**Comment by YassinEldeeb** [comment]
hmm..that's weird. I have all 4 of the above installed with `brew`

**Comment by YassinEldeeb** [comment]
```sh
yassineldeeb@192 uWS-rust-server % brew --prefix openssl
/opt/homebrew/opt/openssl@3
```

still errors with:
```sh
  --- stderr
  src/crypto/openssl.c:34:10: fatal error: 'openssl/ssl.h' file not found
  #include <openssl/ssl.h>
           ^~~~~~~~~~~~~~~
  1 error generated.
```

**Comment by YassinEldeeb** [comment]
Ok, I think I had some weird linking in the installed `openssl` by brew. Upon relinking, I got past the above issue!

**Comment by YassinEldeeb** [comment]
Thanks for guiding! I'll send a PR shortly with documentation update.

**Comment by GenrikhFetischev** [comment]
> Thanks for guiding! I'll send a PR shortly with documentation update.

Thanks for desire to contribute; it would be much appreciated :)

**Comment by YassinEldeeb** [comment]
sorry, for the delay on getting back to you!

I've documented my journey debugging it and getting it to work correctly on my machine.
https://github.com/YassinEldeeb/async_uws

but I'm not sure if the best we can improve this is by documenting OS specific documentation, and I'm trying to find a way to make `async_uws` work without this much configuration.

I'll PR the above documentation if I couldn't find a way to decrease as possible the amount of manual OS setup and system dependencies installations.

Would really appreciate your opinion on this? How can we make `async_uws` work with just its installation without all of the extra configuration?

**Comment by YassinEldeeb** [comment]
I'll open another issue, with the above initiative.
